language: node_js
node_js:
  - 12

services:
  - docker  

#Pre-testing installs
install:
  - echo "nothing needs to be installed"

#Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
#Build
  - docker --version #print the version for logging
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy
#Tagging
  - docker tag udagram-api-feed royalboe/udagram-api-feed:v1
  - docker tag udagram-api-user royalboe/udagram-api-user:v1
  - docker tag udagram-frontend royalboe/udagram-frontend:v3
  - docker tag reverseproxy royalboe/reverseproxy:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push royalboe/udagram-api-feed:v1
  - docker push royalboe/udagram-api-user:v1
  - docker push royalboe/udagram-frontend:v3
  - docker push royalboe/reverseproxy:v1
